{
 "title": "Oxia - Coordinator",
 "tags": [ "oxia" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Oxia Cluster",
    "query": {
     "query": "label_values(oxia_coordinator_node_running, oxia_cluster)"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "oxia_coordinator_leader_election_latency_milliseconds_sum{oxia_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "shard",
    "label": "Shard",
    "query": {
     "query": "oxia_coordinator_leader_election_latency_milliseconds_sum{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes status",
   "type": "status-history",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "sum(oxia_coordinator_node_running{oxia_cluster=\"$cluster\"}) by (node)",
     "legendFormat": "{{node}}"
    }
   ]
  },
  { "title": "Leader Election", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Successful Leader Elections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by(oxia_namespace, shard) (rate(oxia_coordinator_leader_election_latency_milliseconds_count{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\"}[1m])) * 60",
     "legendFormat": "{{oxia_namespace}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Failed Leader Elections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "opm" } },
   "targets": [
    {
     "expr": "sum by (oxia_namespace, shard) (rate(oxia_coordinator_leader_election_failed_total{oxia_cluster=~\"$cluster\",oxia_namespace=~\"$namespace\",  shard=~\"$shard\"}[1m]) * 60)",
     "legendFormat": "{{oxia_namespace}} - {{shard}}"
    }
   ]
  },
  {
   "title": "Leader Election latency - 50pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(oxia_coordinator_leader_election_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\"}) by (le, shard, oxia_namespace))",
     "legendFormat": "{{oxia_namespace}}-{{shard}}"
    }
   ]
  },
  {
   "title": "Leader Election latency - 99pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(oxia_coordinator_leader_election_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\"}) by (le, shard, oxia_namespace))",
     "legendFormat": "{{oxia_namespace}} - {{shard}}"
    }
   ]
  },
  {
   "title": "Leader Election latency - 99.9pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum(oxia_coordinator_leader_election_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\", oxia_namespace=~\"$namespace\", shard=~\"$shard\"}) by (le, shard, oxia_namespace))",
     "legendFormat": "{{oxia_namespace}} - {{shard}}"
    }
   ]
  },
  { "title": "Metadata", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Metadata Write ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "wps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_coordinator_metadata_store_latency_milliseconds_count{oxia_cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Read ops",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(rate(oxia_coordinator_metadata_get_latency_milliseconds_count{oxia_cluster=~\"$cluster\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Write Latency 99pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (oxia_coordinator_metadata_store_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Read Latency 99pct",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (oxia_coordinator_metadata_get_latency_milliseconds_bucket{oxia_cluster=~\"$cluster\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Metadata Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(oxia_coordinator_metadata_size_bytes{oxia_cluster=~\"$cluster\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}