{
 "title": "Oxia - Go Processes",
 "description": "Process status published by Go Prometheus client library, e.g. memory used, fds open, GC details",
 "tags": [ "oxia" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Oxia Cluster",
    "query": {
     "query": "label_values(oxia_coordinator_node_running, oxia_cluster)"
    }
   },
   {
    "name": "component",
    "label": "Component",
    "query": {
     "query": "grpc_server_handled_total{oxia_cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "process_resident_memory_bytes{oxia_cluster=~\"$cluster\", \napp_kubernetes_io_component=~\"$component\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Resident Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Virtual Mem",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "process_virtual_memory_bytes{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}} "
    }
   ]
  },
  {
   "title": "Allocation rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "rate(go_memstats_alloc_bytes_total{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\"}[1m])",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Go Heap Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "go_memstats_heap_alloc_bytes{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration 50pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\", quantile=\"0.5\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration 75pct",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\", quantile=\"0.75\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC duration Max",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "go_gc_duration_seconds{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\", quantile=\"1\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "open fds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "process_open_fds{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "go_goroutines{oxia_cluster=~\"$cluster\", app_kubernetes_io_component=~\"$component\", kubernetes_pod_name=~\"$pod\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}