{
 "title": "Pulsar / BookKeeper",
 "description": "Metrics of bookkeeper cluster",
 "tags": [ "bookkeeper" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(bookie_SERVER_STATUS,job)"
    }
   },
   {
    "name": "instance",
    "label": "Bookie",
    "query": {
     "query": "label_values(bookie_SERVER_STATUS{job=\"$job\"},kubernetes_pod_name)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Healthy", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Writable Bookies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(bookie_SERVER_STATUS{job=~\"$job\"} == 1)\n   "
    }
   ]
  },
  {
   "title": "ReadOnly Bookies",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(bookie_SERVER_STATUS{job=~\"$job\", kubernetes_pod_name=~\"$instance\"} == 0)\n"
    }
   ]
  },
  {
   "title": "Write Rates",
   "type": "timeseries",
   "description": "success rate for different types of requests",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[1m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{success=\"false\"}[1m]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{success=\"true\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "Read Rates",
   "type": "timeseries",
   "description": "success rate for different types of requests",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[1m]))",
     "legendFormat": "Overall"
    },
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{success=\"false\"}[1m]))",
     "legendFormat": "Failure"
    },
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{success=\"true\"}[1m]))",
     "legendFormat": "Success"
    }
   ]
  },
  {
   "title": "writable bookies (percentage)",
   "type": "gauge",
   "gridPos": { "h": 14, "w": 6, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 \n* \ncount(bookie_SERVER_STATUS{job=~\"$job\", kubernetes_pod_name=~\"$instance\"} == 1)\n/\ncount(bookie_SERVER_STATUS{job=~\"$job\", kubernetes_pod_name=~\"$instance\"})\n   "
    }
   ]
  },
  {
   "title": "Throughput (MB / s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(bookie_WRITE_BYTES{job=~\"$job\"}[60s]))",
     "legendFormat": "add entry"
    },
    {
     "expr": "sum(rate(bookie_READ_BYTES{job=~\"$job\"}[60s]))",
     "legendFormat": "read entry"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.99\"})",
     "legendFormat": "add (p99)"
    },
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.999\"})",
     "legendFormat": "add (p999)"
    },
    {
     "expr": "avg(bookkeeper_server_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.5\"})",
     "legendFormat": "add (p50)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.99\"})",
     "legendFormat": "read (p99)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.999\"})",
     "legendFormat": "read (p999)"
    },
    {
     "expr": "avg(bookkeeper_server_READ_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.5\"})",
     "legendFormat": "read (p50)"
    }
   ]
  },
  {
   "title": "Success Rate By Bookie",
   "type": "timeseries",
   "description": "success rate for different types of requests",
   "gridPos": { "h": 7, "w": 9, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} read_entry"
    },
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} add_entry"
    }
   ]
  },
  {
   "title": "Failure Rate by Bookie",
   "type": "timeseries",
   "description": "success rate for different types of requests",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"false\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }} add_entry"
    },
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"false\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}  read_entry"
    }
   ]
  },
  { "title": "Internal Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Write Thread Pool Queue by Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name, thread) (bookkeeper_server_thread_executor_queue{job=~\"$job\", kubernetes_pod_name=~\"$instance\", thread=~\"BookieHighPriorityThread-.*\"})",
     "legendFormat": "{{kubernetes_pod_name}} {{thread}}"
    }
   ]
  },
  {
   "title": "Read Thread Pool Queue by Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by(kubernetes_pod_name, thread) (bookkeeper_server_thread_executor_queue{job=~\"$job\", kubernetes_pod_name=~\"$instance\", thread=~\"BookieReadThreadPool-.*\"})",
     "legendFormat": "{{kubernetes_pod_name}} {{thread}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Write Bytes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(bookie_WRITE_BYTES{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[60s])) by (kubernetes_pod_name) ",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read Bytes (bytes/s)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(bookie_READ_BYTES{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[60s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Add Entry Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[60s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read Entry Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "sum(irate(bookkeeper_server_READ_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[60s])) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Add entry latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Add entry latency (99pct)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 46 },
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Add entry latency (p999)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 46 },
   "targets": [
    {
     "expr": "sum(bookkeeper_server_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.999\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 53 },
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 53 },
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Read entry latency (p999)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 53 },
   "targets": [
    {
     "expr": "sum(bookkeeper_server_READ_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.999\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  { "title": "Journal", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Journal Sync Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 61 },
   "targets": [
    {
     "expr": "sum(irate(bookie_journal_JOURNAL_SYNC_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\"}[60s])) by (kubernetes_pod_name)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Add Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 61 },
   "targets": [
    {
     "expr": "sum(irate(bookie_journal_JOURNAL_ADD_ENTRY_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\"}[60s])) by (kubernetes_pod_name)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_QUEUE_SIZE{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Force Write Queue length",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_FORCE_WRITE_QUEUE_SIZE{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 75 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 75 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Journal Add latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 75 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_ADD_ENTRY{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"1.0\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (p50)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.5\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 82 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"0.99\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Journal Sync Latency (Max)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 82 },
   "targets": [
    {
     "expr": "sum(bookie_journal_JOURNAL_SYNC{job=~\"$job\", kubernetes_pod_name=~\"$instance\", success=\"true\", quantile=\"1.0\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  { "title": "Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 89 } },
  {
   "title": "Ledgers count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 90 },
   "targets": [
    {
     "expr": "sum(bookie_ledgers_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Entries count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 90 },
   "targets": [
    {
     "expr": "sum(bookie_entries_count{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Write Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 97 },
   "targets": [
    {
     "expr": "sum(bookie_write_cache_size{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 97 },
   "targets": [
    {
     "expr": "sum(bookie_read_cache_size{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Read Cache Miss-to-Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(irate(bookie_read_cache_misses{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[1m])) by (kubernetes_pod_name) / sum(irate(bookie_read_cache_hits{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}[1m])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Entries Read from Disk per Read Op",
   "type": "timeseries",
   "description": "If >1 indicates read cache thrashing.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 104 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "(sum(rate(bookie_readahead_batch_count_count[1m])) by (kubernetes_pod_name) + sum(rate(bookie_readahead_batch_count_sum[1m])) by (kubernetes_pod_name)) / sum(rate(bookie_read_entry_count[1m])) by (kubernetes_pod_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Deleted Ledger Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 111 },
   "targets": [
    {
     "expr": "sum(bookie_DELETED_LEDGER_TOTAL{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Writable Ledger Directory Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 111 },
   "targets": [
    {
     "expr": "sum(bookie_ledger_writable_dirs{job=~\"$job\", kubernetes_pod_name=~\"$instance\"}) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  }
 ]
}