{
 "title": "Pulsar / Broker Cache",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "In/Out Rate vs Cache Hit/Miss Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(pulsar_ml_cache_hits_rate)", "legendFormat": "Cache Hit" },
    {
     "expr": "sum(pulsar_ml_cache_misses_rate)",
     "legendFormat": "Miss Rate"
    },
    {
     "expr": "sum(avg(pulsar_rate_in) by (topic))",
     "legendFormat": "Rate In"
    },
    {
     "expr": "sum(avg(pulsar_rate_out) by (topic))",
     "legendFormat": "Rate Out"
    }
   ]
  },
  {
   "title": "Cache Hit Percentage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_hits_rate) / (sum(pulsar_ml_cache_hits_rate) + sum(pulsar_ml_cache_misses_rate)) * 100",
     "legendFormat": "Cache Hit %"
    }
   ]
  },
  {
   "title": "Cache Miss Rate by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_misses_rate) by (kubernetes_pod_name)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "Cache Hit Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_hits_rate) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Hits Throughput by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_hits_throughput) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Misses Throughput by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_misses_throughput) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Used Size By Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_used_size) by (kubernetes_pod_name)"
    }
   ]
  },
  {
   "title": "Evictions by Broker",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(pulsar_ml_cache_evictions) by (kubernetes_pod_name)"
    }
   ]
  }
 ]
}