{
 "title": "Pulsar Offloader",
 "tags": [ "pulsar" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {
     "query": "{cluster=~\".+\"}"
    }
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "pulsar_rate_in{namespace=~\".+\", cluster=~\"$cluster\"}"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "pulsar_storage_size{job=~\".+\"}"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "pulsar_ledgeroffloader_writeError",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pulsar_ledgeroffloader_writeError{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "pulsar_ledgeroffloader_readLedgerLatencyBuckets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "pulsar_ledgeroffloader_readLedgerLatencyBuckets{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "pulsar_ledgeroffloader_readOffloadError",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "pulsar_ledgeroffloader_readOffloadError{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "pulsar_ledgeroffloader_writeRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "pulsar_ledgeroffloader_writeRate{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "pulsar_ledgeroffloader_offloadError",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pulsar_ledgeroffloader_offloadError{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "pulsar_ledgeroffloader_readOffloadRate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "pulsar_ledgeroffloader_readOffloadRate{cluster=~\"$cluster\",namespace=~\"$namespace\",job=~\"$job\"}"
    }
   ]
  }
 ]
}